# Generated by CloudSDD (RFC 018) for go 1.24. Do not edit:
# this file is regenerated on every build and is not read from the
# repository. Base images are pinned by digest in
# internal/provider/pipeline/generator.go.
#
# Expects: a main package at the repository root, plus go.mod (and go.sum).

FROM golang:1.24-bookworm@sha256:1a6d4452c65dea36aac2e2d606b01b4a029ec90cc1ae53890540ce6173ea77ac AS build
WORKDIR /src

# Dependencies first, so a source-only change does not re-download them.
# The bracket makes go.sum optional: a module with no dependencies has none,
# and a COPY that fails on its absence would refuse to build one.
COPY go.mod go.su[m] ./
RUN go mod download

COPY . .
# CGO off is what makes the binary static, and therefore what makes the
# distroless final stage possible. -trimpath keeps build paths out of the
# binary; -s -w drops the symbol table.
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/app .

FROM gcr.io/distroless/static-debian12:nonroot@sha256:f5b485ea962d9bd1186b2f6b3a061191539b905b82ec395de78cbfae51f20e35
COPY --from=build /out/app /app

EXPOSE 8080
EXPOSE 9090
USER 65532:65532
ENTRYPOINT ["/app"]
