# Generated by CloudSDD (RFC 018) for java 21. Do not edit:
# this file is regenerated on every build and is not read from the
# repository. Base images are pinned by digest in
# internal/provider/pipeline/generator.go.
#
# Expects: a Maven project with the wrapper (./mvnw) producing target/*.jar.

FROM eclipse-temurin:21-jdk@sha256:efd34b940f2d5a621605c8531c2afb7759c936b6c2ef637a69aa3bf3e1e789d1 AS build
WORKDIR /src

COPY . .
# Tests run in CI, not in the image build: a build that reruns them here
# would fail deployments for reasons that have nothing to do with the image.
RUN ./mvnw --batch-mode --no-transfer-progress -DskipTests package

FROM gcr.io/distroless/java21-debian12:nonroot@sha256:7e37784d94dccbf5ccb195c73b295f5ad00cd266512dfbac12eb9c3c28f8077d
WORKDIR /app
COPY --from=build /src/target/*.jar /app/app.jar

EXPOSE 8080
USER 65532:65532
CMD ["/app/app.jar"]
