# Generated by CloudSDD (RFC 018) for node 22. Do not edit:
# this file is regenerated on every build and is not read from the
# repository. Base images are pinned by digest in
# internal/provider/pipeline/generator.go.
#
# Expects: package.json with a "start" script, and package-lock.json.

FROM node:22-bookworm@sha256:0557ac14e0d45d02ed563067b82856ca5e7aa3437fa28d98d4350ea9c3d9494a AS build
WORKDIR /src

COPY package.json package-lock.json ./
# --omit=dev keeps test and build tooling out of what ships. ci rather than
# install so the lockfile decides, not the registry's newest match — which
# is also why the lockfile is copied rather than treated as optional.
RUN npm ci --omit=dev

COPY . .

FROM node:22-bookworm-slim@sha256:d649c27dae7ba0137b3cef5dd75baa422c08dc3d9e3fc0c23dfb172dc3cc6436
# The official image carries a "node" user, but at uid 1000. A user is
# created here instead so that every runtime CloudSDD generates shares one
# uid and a volume written by one image stays readable by another (RFC 018
# §2.7).
RUN groupadd --system --gid 65532 app \
 && useradd --system --uid 65532 --gid app --no-create-home --shell /usr/sbin/nologin app

WORKDIR /app
COPY --from=build --chown=65532:65532 /src /app
ENV NODE_ENV=production

EXPOSE 3000
USER 65532:65532
ENTRYPOINT ["npm", "start"]
