# Generated by CloudSDD (RFC 018) for python 3.12. Do not edit:
# this file is regenerated on every build and is not read from the
# repository. Base images are pinned by digest in
# internal/provider/pipeline/generator.go.
#
# Expects: requirements.txt and main.py at the repository root.

FROM python:3.12-bookworm@sha256:3cd9086bdb30f7c9bc08a3fa621d9842e0d3f6f9291aeb4677e0547817c10b12 AS build
WORKDIR /src

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

FROM python:3.12-slim-bookworm@sha256:4766d8b510c428e595d74b9cc5bbb2fae8e26316fffb4adc89908d79aacd58a2
# The slim image ships no unprivileged user, so one is created here. The uid
# matches distroless's "nonroot" so a shared volume stays readable across
# runtimes (RFC 018 §2.7).
RUN groupadd --system --gid 65532 app \
 && useradd --system --uid 65532 --gid app --no-create-home --shell /usr/sbin/nologin app

WORKDIR /app
COPY --from=build /opt/venv /opt/venv
COPY --from=build --chown=65532:65532 /src /app

ENV PATH="/opt/venv/bin:$PATH" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

EXPOSE 8000
USER 65532:65532
ENTRYPOINT ["python", "main.py"]
